classdef BenchmarkAnalysis2d_Elastic_Sidesway_Uninhibited < BenchmarkAnalysis2d_Elastic_Base
    
    properties (SetAccess = immutable)
        EI      % Elastic flexural stiffness
        L       % Length of the member
        K       % Effective Length Factor        
        kqtop   % Stiffness of the top rotational spring
        kqbot   % Stiffness of the bottom rotational spring
        gamma   % Leaning column load ratio
        delta0  % Initial out-of-straightness
        Delta0  % Initial out-of-plumbness
    end
    
    properties
        includeInitialGeometricImperfections = true;
    end
    
    methods
        function obj = BenchmarkAnalysis2d_Elastic_Sidesway_Uninhibited(EI,L,kqtop,kqbot,gamma,delta0,Delta0)
            if nargin == 1
                data = EI;
                obj.EI      = data.EI;
                obj.L       = data.L;       
                obj.kqtop   = data.kqtop;
                obj.kqbot   = data.kqbot;
                obj.gamma   = data.gamma;
                obj.delta0  = data.delta0;
                obj.Delta0  = data.Delta0;
            else
                obj.EI      = EI;
                obj.L       = L;       
                obj.kqtop   = kqtop;
                obj.kqbot   = kqbot;
                obj.gamma   = gamma;
                obj.delta0  = delta0;
                obj.Delta0  = Delta0;
            end

            obj.K       = obj.compute_K;
        end
        function Hwnl = Hwnl(obj,P,H,notionalLoadObject)
            Ptotal = (1+obj.gamma)*P;
            B2     = obj.driftRatio(P);
            Hwnl   = notionalLoadObject.HwithNotionalLoad(H,Ptotal,B2);
        end
        function g = Gtop(obj)
            g = (6*obj.EI)/(obj.kqtop*obj.L);
        end
        function g = Gbot(obj)
            g = (6*obj.EI)/(obj.kqbot*obj.L);
        end
        function k = storyBasedK(obj)
            k = sqrt(1+obj.gamma)*nomographK_sidesway_uninhibited(obj.Gtop,obj.Gbot);
        end
        function k = compute_K(obj)
            options = optimoptions('fsolve',...
                'Display','off',...
                'TolFun',min([abs(errorK(obj,obj.storyBasedK))/1e12 0.01]));
            [k,~,exitflag] = fsolve(@(k)errorK(obj,k),obj.storyBasedK,options);
            if exitflag <= 0
                options = optimoptions('fsolve',...
                    'Display','off',...
                    'TolFun',min([abs(errorK(obj,1))/1e12 0.01]));
                [k,~,exitflag] = fsolve(@(k)errorK(obj,k),1,options);
                assert(exitflag >= 1,'Could not deterine K');
            end
        end
        function x = endMomentRatio(obj,P)
            m1 = obj.firstOrderMoment(P,1,0);
            m2 = obj.firstOrderMoment(P,1,obj.L);
            if abs(m1) > abs(m2)
                x = -m2/m1;
            else
                x = -m1/m2;
            end
        end   
        function x = driftRatio(obj,P)
            x = obj.secondOrderDisplacement(P,1,obj.L)/obj.firstOrderDisplacement(P,1,obj.L);
        end  
        function v = firstOrderDisplacement(obj,P,H,x)
            if nargin < 4
                x = obj.position;
            end
            
            if P > 0
                error('Function only valid for compressive loads, P = %g',P);
            else
                % Compressive loads should be positive
                P = -P; 
            end
            
            alpha = sqrt(P/obj.EI);
            if obj.includeInitialGeometricImperfections
                if obj.kqtop == 0
                    if obj.kqbot == 0
                        error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
                    elseif obj.kqbot == Inf
                        v = (1/6).*obj.EI.^(-1).*obj.L.^(-1).*pi.^(-2).*(pi.*x.*((H.*obj.L+obj.Delta0.*obj.gamma.* ...
                            P).*pi.*(3.*obj.L+(-1).*x).*x+(-1).*alpha.^2.*obj.EI.*(6.*obj.delta0.*obj.L.^2+ ...
                            obj.Delta0.*pi.*x.*((-3).*obj.L+x)))+6.*alpha.^2.*obj.delta0.*obj.EI.*obj.L.^3.*sin( ...
                            obj.L.^(-1).*pi.*x));
                    else
                        v = (1/6).*obj.EI.^(-1).*obj.kqbot.^(-1).*obj.L.^(-1).*pi.^(-2).*(pi.*x.*((H.*obj.L+ ...
                            obj.Delta0.*obj.gamma.*P).*pi.*(6.*obj.EI.*obj.L+obj.kqbot.*(3.*obj.L+(-1).*x).*x)+ ...
                            alpha.^2.*obj.EI.*((-6).*obj.delta0.*obj.kqbot.*obj.L.^2+obj.Delta0.*pi.*(6.*obj.EI.*obj.L+ ...
                            obj.kqbot.*(3.*obj.L+(-1).*x).*x)))+6.*alpha.^2.*obj.delta0.*obj.EI.*obj.kqbot.*obj.L.^3.* ...
                            sin(obj.L.^(-1).*pi.*x));
                    end
                elseif obj.kqtop == Inf
                    if obj.kqbot == 0
                        v = (1/6).*obj.EI.^(-1).*obj.L.^(-1).*pi.^(-2).*(pi.*x.*((H.*obj.L+obj.Delta0.*obj.gamma.* ...
                            P).*pi.*(3.*obj.L.^2+(-1).*x.^2)+alpha.^2.*obj.EI.*(3.*obj.L.^2.*(2.*obj.delta0+ ...
                            obj.Delta0.*pi)+(-1).*obj.Delta0.*pi.*x.^2))+6.*alpha.^2.*obj.delta0.*obj.EI.* ...
                            obj.L.^3.*sin(obj.L.^(-1).*pi.*x));
                    elseif obj.kqbot == Inf
                        v = (1/12).*obj.EI.^(-1).*obj.L.^(-1).*pi.^(-2).*(pi.*x.*((H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P).*pi.*(3.*obj.L+(-2).*x).*x+alpha.^2.*obj.EI.*(obj.Delta0.*pi.*(3.*obj.L+ ...
                            (-2).*x).*x+12.*obj.delta0.*obj.L.*((-1).*obj.L+x)))+12.*alpha.^2.*obj.delta0.* ...
                            obj.EI.*obj.L.^3.*sin(obj.L.^(-1).*pi.*x));
                    else
                        v = (1/12).*obj.EI.^(-1).*obj.L.^(-1).*(obj.EI+obj.kqbot.*obj.L).^(-1).*pi.^(-2).*(pi.*x.* ...
                            ((H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.*(6.*obj.EI.*obj.L.^2+3.*obj.kqbot.*obj.L.^2.*x+(-2) ...
                            .*(obj.EI+obj.kqbot.*obj.L).*x.^2)+alpha.^2.*obj.EI.*(12.*obj.delta0.*obj.L.^2.*(obj.EI+(-1).* ...
                            obj.kqbot.*obj.L+obj.kqbot.*x)+obj.Delta0.*pi.*(6.*obj.EI.*obj.L.^2+3.*obj.kqbot.*obj.L.^2.*x+(-2) ...
                            .*(obj.EI+obj.kqbot.*obj.L).*x.^2)))+12.*alpha.^2.*obj.delta0.*obj.EI.*obj.L.^3.*(obj.EI+ ...
                            obj.kqbot.*obj.L).*sin(obj.L.^(-1).*pi.*x));
                    end
                else
                    if obj.kqbot == 0
                        v = (1/6).*obj.EI.^(-1).*obj.kqtop.^(-1).*obj.L.^(-1).*pi.^(-2).*(pi.*x.*(3.*obj.L.*( ...
                            2.*alpha.^2.*obj.delta0.*obj.EI.*obj.kqtop.*obj.L+(2.*obj.EI+obj.kqtop.*obj.L).*(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi)+(-1).*obj.kqtop.*(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.*x.^2)+6.*alpha.^2.*obj.delta0.* ...
                            obj.EI.*obj.kqtop.*obj.L.^3.*sin(obj.L.^(-1).*pi.*x));
                    elseif obj.kqbot == Inf
                        v = (1/12).*obj.EI.^(-1).*obj.L.^(-1).*(obj.EI+obj.kqtop.*obj.L).^(-1).*pi.^(-2).*(pi.*x.* ...
                            ((H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.*x.*(3.*obj.L.*(2.*obj.EI+obj.kqtop.*obj.L)+(-2).*( ...
                            obj.EI+obj.kqtop.*obj.L).*x)+alpha.^2.*obj.EI.*((-12).*obj.delta0.*obj.L.^2.*(obj.EI+obj.kqtop.*obj.L+ ...
                            (-1).*obj.kqtop.*x)+obj.Delta0.*pi.*x.*(3.*obj.L.*(2.*obj.EI+obj.kqtop.*obj.L)+(-2).*(obj.EI+ ...
                            obj.kqtop.*obj.L).*x)))+12.*alpha.^2.*obj.delta0.*obj.EI.*obj.L.^3.*(obj.EI+obj.kqtop.*obj.L).* ...
                            sin(obj.L.^(-1).*pi.*x));
                    else
                        v = (1/12).*obj.EI.^(-1).*obj.L.^(-1).*(obj.EI.*(obj.kqbot+obj.kqtop)+obj.kqbot.*obj.kqtop.*obj.L).^( ...
                            -1).*pi.^(-2).*(pi.*x.*(6.*obj.EI.*obj.L.*((-2).*alpha.^2.*obj.delta0.*obj.L.*( ...
                            obj.EI.*(obj.kqbot+(-1).*obj.kqtop)+obj.kqbot.*obj.kqtop.*obj.L)+(2.*obj.EI+obj.kqtop.*obj.L).*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi)+3.*obj.kqbot.*obj.L.*(4.* ...
                            alpha.^2.*obj.delta0.*obj.EI.*obj.kqtop.*obj.L+(2.*obj.EI+obj.kqtop.*obj.L).*(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi).*x+(-2).*(obj.EI.*(obj.kqbot+obj.kqtop) ...
                            +obj.kqbot.*obj.kqtop.*obj.L).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).* ...
                            pi.*x.^2)+12.*alpha.^2.*obj.delta0.*obj.EI.*obj.L.^3.*(obj.EI.*(obj.kqbot+obj.kqtop)+ ...
                            obj.kqbot.*obj.kqtop.*obj.L).*sin(obj.L.^(-1).*pi.*x));
                    end
                end
            else
                if obj.kqtop == 0
                    if obj.kqbot == 0
                        error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
                    elseif obj.kqbot == Inf
                        v = (1/6).*obj.EI.^(-1).*H.*(3.*obj.L+(-1).*x).*x.^2;
                    else
                        v = (1/6).*obj.EI.^(-1).*H.*obj.kqbot.^(-1).*x.*(6.*obj.EI.*obj.L+obj.kqbot.*(3.*obj.L+(-1).* ...
                            x).*x);
                    end
                elseif obj.kqtop == Inf
                    if obj.kqbot == 0
                        v = (1/6).*obj.EI.^(-1).*H.*(3.*obj.L.^2.*x+(-1).*x.^3);
                    elseif obj.kqbot == Inf
                        v = (1/12).*obj.EI.^(-1).*H.*(3.*obj.L+(-2).*x).*x.^2;
                    else
                        v = (1/12).*obj.EI.^(-1).*H.*(obj.EI+obj.kqbot.*obj.L).^(-1).*x.*(6.*obj.EI.*obj.L.^2+3.* ...
                            obj.kqbot.*obj.L.^2.*x+(-2).*(obj.EI+obj.kqbot.*obj.L).*x.^2);
                    end
                else
                    if obj.kqbot == 0
                        v = (1/6).*obj.EI.^(-1).*H.*obj.kqtop.^(-1).*x.*(6.*obj.EI.*obj.L+3.*obj.kqtop.*obj.L.^2+(-1) ...
                            .*obj.kqtop.*x.^2);
                    elseif obj.kqbot == Inf
                        v = (1/12).*obj.EI.^(-1).*H.*(obj.EI+obj.kqtop.*obj.L).^(-1).*x.^2.*(3.*obj.L.*(2.*obj.EI+ ...
                            obj.kqtop.*obj.L)+(-2).*(obj.EI+obj.kqtop.*obj.L).*x);
                    else
                        v = (1/12).*obj.EI.^(-1).*H.*(obj.EI.*(obj.kqbot+obj.kqtop)+obj.kqbot.*obj.kqtop.*obj.L).^(-1).* ...
                            x.*(6.*obj.EI.*obj.L.*(2.*obj.EI+obj.kqtop.*obj.L)+3.*obj.kqbot.*obj.L.*(2.*obj.EI+obj.kqtop.*obj.L).*x+( ...
                            -2).*(obj.EI.*(obj.kqbot+obj.kqtop)+obj.kqbot.*obj.kqtop.*obj.L).*x.^2);
                    end
                end                
            end
        end
        function v = secondOrderDisplacement(obj,P,H,x)
            if nargin < 4
                x = obj.position;
            end            
            
            % Check for zero axial load case
            if P == 0
                v = obj.firstOrderDisplacement(P,H,x);
                return
            elseif P > 0
                error('Function only valid for compressive loads, P = %g',P);
            else
                % Compressive loads should be positive
                P = -P; 
            end
            
            alpha = sqrt(P/obj.EI);
            if obj.includeInitialGeometricImperfections
                if obj.kqtop == 0
                    if obj.kqbot == 0
                        error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
                    elseif obj.kqbot == Inf
                        v = ((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*(alpha.*obj.L.*(alpha.^2.*obj.EI+ ...
                            obj.gamma.*P).*cos(alpha.*obj.L)+(-1).*obj.gamma.*P.*sin(alpha.*obj.L)).^(-1).*(( ...
                            alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+ ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(-1).*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*sin(alpha.*( ...
                            obj.L+(-1).*x))+sin(alpha.*obj.L).*((H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2+(-1).* ...
                            alpha.^4.*obj.EI.*obj.L.^2.*(obj.Delta0+obj.delta0.*pi)+(-1).*alpha.^2.*(H.*obj.L.^3+ ...
                            obj.Delta0.*(obj.gamma.*obj.L.^2.*P+(-1).*obj.EI.*pi.^2)+obj.delta0.*obj.gamma.*obj.L.*P.*pi.* ...
                            (obj.L+(-1).*x))+(-1).*alpha.^2.*obj.delta0.*obj.gamma.*obj.L.^2.*P.*sin(obj.L.^(-1).* ...
                            pi.*x))+alpha.*cos(alpha.*obj.L).*((alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P).*(alpha.*obj.L+(-1).*pi).*(alpha.*obj.L+pi).*x+alpha.^2.* ...
                            obj.delta0.*obj.L.^3.*(alpha.^2.*obj.EI+obj.gamma.*P).*sin(obj.L.^(-1).*pi.*x)));
                    else
                        v = ((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-1).*alpha.*obj.kqbot.*obj.L.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*cos(alpha.*obj.L)+(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*( ...
                            obj.kqbot+alpha.^2.*obj.EI.*obj.L).*P).*sin(alpha.*obj.L)).^(-1).*(obj.kqbot.*((-1).* ...
                            alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+(-1) ...
                            .*alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*sin(alpha.*(obj.L+(-1).*x)) ...
                            +alpha.*obj.kqbot.*cos(alpha.*obj.L).*((alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P).*((-1).*alpha.*obj.L+pi).*(alpha.*obj.L+pi).*x+(-1).*alpha.^2.* ...
                            obj.delta0.*obj.L.^3.*(alpha.^2.*obj.EI+obj.gamma.*P).*sin(obj.L.^(-1).*pi.*x))+sin( ...
                            alpha.*obj.L).*(obj.kqbot.*(alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+ ...
                            obj.Delta0.*obj.gamma.*P)+alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P) ...
                            .*pi+(-1).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2)+ ...
                            alpha.^2.*(alpha.^2.*obj.EI.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P)+(-1).*obj.delta0.*obj.gamma.*obj.kqbot.*obj.L.*P.*pi+(-1).*obj.EI.*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*x+alpha.^2.* ...
                            obj.delta0.*obj.L.^2.*(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*(obj.kqbot+alpha.^2.*obj.EI.*obj.L).* ...
                            P).*sin(obj.L.^(-1).*pi.*x)));
                    end
                elseif obj.kqtop == Inf
                    if obj.kqbot == 0
                        v = ((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-1).*obj.gamma.*P+alpha.*obj.L.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*cot(alpha.*obj.L)).^(-1).*(((-1).*alpha.^2.* ...
                            obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+alpha.^2.* ...
                            obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.*obj.Delta0.*obj.EI+ ...
                            H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*csc(alpha.*obj.L).*sin(alpha.*x)+(-1) ...
                            .*alpha.^2.*obj.delta0.*obj.gamma.*obj.L.*P.*(pi.*x+obj.L.*sin(obj.L.^(-1).*pi.*x))+ ...
                            cot(alpha.*obj.L).*(alpha.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.* ...
                            P).*(alpha.*obj.L+(-1).*pi).*(alpha.*obj.L+pi).*x+alpha.^3.*obj.delta0.*obj.L.^3.* ...
                            (alpha.^2.*obj.EI+obj.gamma.*P).*sin(obj.L.^(-1).*pi.*x)));
                    elseif obj.kqbot == Inf
                        v = (1/2).*((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-2).*obj.gamma.*P+alpha.* ...
                            obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cot((1/2).*alpha.*obj.L)).^(-1).*(csc(( ...
                            1/2).*alpha.*obj.L).^2.*((-1).*alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+ ...
                            H.*obj.L+obj.Delta0.*obj.gamma.*P)+alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+ ...
                            obj.gamma.*P).*pi+(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2+ ...
                            (alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+ ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(-1).*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*obj.L) ...
                            +((-1).*alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.* ...
                            P)+(-1).*alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*( ...
                            obj.L+(-1).*x))+(-1).*((-1).*alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.* ...
                            obj.L+obj.Delta0.*obj.gamma.*P)+alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.* ...
                            P).*pi+(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos( ...
                            alpha.*x)+alpha.*((-2).*obj.delta0.*obj.gamma.*obj.L.*P.*pi+(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*(alpha.*obj.L+(-1).*pi).*(alpha.*obj.L+ ...
                            pi).*x).*sin(alpha.*obj.L)+2.*alpha.*obj.delta0.*obj.gamma.*obj.L.*P.*pi.*sin( ...
                            alpha.*(obj.L+(-1).*x))+2.*alpha.*obj.delta0.*obj.gamma.*obj.L.*P.*pi.*sin(alpha.* ...
                            x))+2.*alpha.^2.*obj.delta0.*obj.L.^2.*((-2).*obj.gamma.*P+alpha.*obj.L.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*cot((1/2).*alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x) ...
                            );
                    else
                        v = ((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-2).*obj.gamma.*obj.kqbot.*P+(2.* ...
                            obj.gamma.*obj.kqbot.*P+alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*cos( ...
                            alpha.*obj.L)+alpha.*(alpha.^2.*obj.EI.*obj.kqbot.*obj.L+(-1).*obj.EI.*obj.gamma.*P+ ...
                            obj.gamma.*obj.kqbot.*obj.L.*P).*sin(alpha.*obj.L)).^(-1).*(obj.kqbot.*((-1).* ...
                            alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+ ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2)+obj.kqbot.*((-1).*alpha.^2.* ...
                            obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+(-1).* ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*(obj.L+(-1).*x)) ...
                            +alpha.^4.*obj.Delta0.*obj.EI.*obj.kqbot.*obj.L.^2.*cos(alpha.*x)+alpha.^2.*H.* ...
                            obj.kqbot.*obj.L.^3.*cos(alpha.*x)+alpha.^2.*obj.Delta0.*obj.gamma.*obj.kqbot.*obj.L.^2.* ...
                            P.*cos(alpha.*x)+(-1).*alpha.^4.*obj.delta0.*obj.EI.*obj.kqbot.*obj.L.^2.*pi.*cos( ...
                            alpha.*x)+(-1).*alpha.^2.*obj.delta0.*obj.gamma.*obj.kqbot.*obj.L.^2.*P.*pi.*cos( ...
                            alpha.*x)+(-1).*alpha.^2.*obj.Delta0.*obj.EI.*obj.kqbot.*pi.^2.*cos(alpha.*x)+ ...
                            (-1).*H.*obj.kqbot.*obj.L.*pi.^2.*cos(alpha.*x)+(-1).*obj.Delta0.*obj.gamma.* ...
                            obj.kqbot.*P.*pi.^2.*cos(alpha.*x)+(-2).*alpha.*obj.delta0.*obj.gamma.*obj.kqbot.* ...
                            obj.L.*P.*pi.*sin(alpha.*obj.L)+alpha.^5.*obj.Delta0.*obj.EI.*obj.kqbot.*obj.L.^2.*x.*sin( ...
                            alpha.*obj.L)+alpha.^3.*H.*obj.kqbot.*obj.L.^3.*x.*sin(alpha.*obj.L)+alpha.^3.* ...
                            obj.Delta0.*obj.gamma.*obj.kqbot.*obj.L.^2.*P.*x.*sin(alpha.*obj.L)+(-1).*alpha.^3.* ...
                            obj.delta0.*obj.EI.*obj.gamma.*obj.L.*P.*pi.*x.*sin(alpha.*obj.L)+(-1).*alpha.^3.* ...
                            obj.Delta0.*obj.EI.*obj.kqbot.*pi.^2.*x.*sin(alpha.*obj.L)+(-1).*alpha.*H.*obj.kqbot.* ...
                            obj.L.*pi.^2.*x.*sin(alpha.*obj.L)+(-1).*alpha.*obj.Delta0.*obj.gamma.*obj.kqbot.*P.* ...
                            pi.^2.*x.*sin(alpha.*obj.L)+2.*alpha.*obj.delta0.*obj.gamma.*obj.kqbot.*obj.L.*P.*pi.* ...
                            sin(alpha.*(obj.L+(-1).*x))+(-1).*alpha.^5.*obj.Delta0.*obj.EI.^2.*obj.L.^2.*sin( ...
                            alpha.*x)+(-1).*alpha.^3.*obj.EI.*H.*obj.L.^3.*sin(alpha.*x)+(-1).* ...
                            alpha.^3.*obj.Delta0.*obj.EI.*obj.gamma.*obj.L.^2.*P.*sin(alpha.*x)+alpha.^5.* ...
                            obj.delta0.*obj.EI.^2.*obj.L.^2.*pi.*sin(alpha.*x)+2.*alpha.*obj.delta0.*obj.gamma.* ...
                            obj.kqbot.*obj.L.*P.*pi.*sin(alpha.*x)+alpha.^3.*obj.delta0.*obj.EI.*obj.gamma.*obj.L.^2.* ...
                            P.*pi.*sin(alpha.*x)+alpha.^3.*obj.Delta0.*obj.EI.^2.*pi.^2.*sin(alpha.*x) ...
                            +alpha.*obj.EI.*H.*obj.L.*pi.^2.*sin(alpha.*x)+alpha.*obj.Delta0.*obj.EI.*obj.gamma.* ...
                            P.*pi.^2.*sin(alpha.*x)+alpha.^2.*obj.delta0.*obj.L.^2.*((-2).*obj.gamma.* ...
                            obj.kqbot.*P+alpha.*(alpha.^2.*obj.EI.*obj.kqbot.*obj.L+(-1).*obj.EI.*obj.gamma.*P+obj.gamma.* ...
                            obj.kqbot.*obj.L.*P).*sin(alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x)+cos(alpha.*obj.L).*( ...
                            obj.kqbot.*(alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.* ...
                            P)+alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(-1).*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2)+alpha.^2.*obj.EI.* ...
                            (alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*(alpha.*obj.L+(-1).*pi) ...
                            .*(alpha.*obj.L+pi).*x+alpha.^2.*obj.delta0.*obj.L.^2.*(2.*obj.gamma.*obj.kqbot.*P+ ...
                            alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*sin(obj.L.^(-1).*pi.*x)));
                    end
                else
                    if obj.kqbot == 0
                        v = ((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*( ...
                            obj.kqtop+alpha.^2.*obj.EI.*obj.L).*P+(-1).*alpha.*obj.kqtop.*obj.L.*(alpha.^2.*obj.EI+ ...
                            obj.gamma.*P).*cot(alpha.*obj.L)).^(-1).*((-1).*obj.kqtop.*((-1).*alpha.^2.* ...
                            obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+alpha.^2.* ...
                            obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.*obj.Delta0.*obj.EI+ ...
                            H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*csc(alpha.*obj.L).*sin(alpha.*x)+ ...
                            alpha.*obj.kqtop.*cot(alpha.*obj.L).*((alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P).*((-1).*alpha.*obj.L+pi).*(alpha.*obj.L+pi).*x+(-1).*alpha.^2.* ...
                            obj.delta0.*obj.L.^3.*(alpha.^2.*obj.EI+obj.gamma.*P).*sin(obj.L.^(-1).*pi.*x))+ ...
                            alpha.^2.*((alpha.^2.*obj.EI.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+ ...
                            obj.Delta0.*obj.gamma.*P)+obj.delta0.*obj.gamma.*obj.kqtop.*obj.L.*P.*pi+(-1).*obj.EI.*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*x+obj.delta0.* ...
                            obj.L.^2.*(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*(obj.kqtop+alpha.^2.*obj.EI.*obj.L).*P).*sin( ...
                            obj.L.^(-1).*pi.*x)));
                    elseif obj.kqbot == Inf
                        v = ((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-2).*obj.gamma.*obj.kqtop.*P+(2.* ...
                            obj.gamma.*obj.kqtop.*P+alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*cos( ...
                            alpha.*obj.L)+alpha.*(alpha.^2.*obj.EI.*obj.kqtop.*obj.L+(-1).*obj.EI.*obj.gamma.*P+ ...
                            obj.gamma.*obj.kqtop.*obj.L.*P).*sin(alpha.*obj.L)).^(-1).*(obj.kqtop.*((-1).* ...
                            alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+ ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2)+obj.kqtop.*((-1).*alpha.^2.* ...
                            obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+(-1).* ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*(obj.L+(-1).*x)) ...
                            +alpha.^4.*obj.Delta0.*obj.EI.*obj.kqtop.*obj.L.^2.*cos(alpha.*x)+alpha.^2.*H.* ...
                            obj.kqtop.*obj.L.^3.*cos(alpha.*x)+alpha.^2.*obj.Delta0.*obj.gamma.*obj.kqtop.*obj.L.^2.* ...
                            P.*cos(alpha.*x)+(-1).*alpha.^4.*obj.delta0.*obj.EI.*obj.kqtop.*obj.L.^2.*pi.*cos( ...
                            alpha.*x)+(-1).*alpha.^2.*obj.delta0.*obj.gamma.*obj.kqtop.*obj.L.^2.*P.*pi.*cos( ...
                            alpha.*x)+(-1).*alpha.^2.*obj.Delta0.*obj.EI.*obj.kqtop.*pi.^2.*cos(alpha.*x)+ ...
                            (-1).*H.*obj.kqtop.*obj.L.*pi.^2.*cos(alpha.*x)+(-1).*obj.Delta0.*obj.gamma.* ...
                            obj.kqtop.*P.*pi.^2.*cos(alpha.*x)+(-1).*alpha.^5.*obj.Delta0.*obj.EI.^2.* ...
                            obj.L.^2.*sin(alpha.*obj.L)+(-1).*alpha.^3.*obj.EI.*H.*obj.L.^3.*sin(alpha.*obj.L)+( ...
                            -1).*alpha.^3.*obj.Delta0.*obj.EI.*obj.gamma.*obj.L.^2.*P.*sin(alpha.*obj.L)+(-1).* ...
                            alpha.^5.*obj.delta0.*obj.EI.^2.*obj.L.^2.*pi.*sin(alpha.*obj.L)+(-2).*alpha.* ...
                            obj.delta0.*obj.gamma.*obj.kqtop.*obj.L.*P.*pi.*sin(alpha.*obj.L)+(-1).*alpha.^3.* ...
                            obj.delta0.*obj.EI.*obj.gamma.*obj.L.^2.*P.*pi.*sin(alpha.*obj.L)+alpha.^3.*obj.Delta0.* ...
                            obj.EI.^2.*pi.^2.*sin(alpha.*obj.L)+alpha.*obj.EI.*H.*obj.L.*pi.^2.*sin(alpha.*obj.L)+ ...
                            alpha.*obj.Delta0.*obj.EI.*obj.gamma.*P.*pi.^2.*sin(alpha.*obj.L)+alpha.^5.* ...
                            obj.Delta0.*obj.EI.*obj.kqtop.*obj.L.^2.*x.*sin(alpha.*obj.L)+alpha.^3.*H.*obj.kqtop.* ...
                            obj.L.^3.*x.*sin(alpha.*obj.L)+alpha.^3.*obj.Delta0.*obj.gamma.*obj.kqtop.*obj.L.^2.*P.* ...
                            x.*sin(alpha.*obj.L)+alpha.^3.*obj.delta0.*obj.EI.*obj.gamma.*obj.L.*P.*pi.*x.*sin( ...
                            alpha.*obj.L)+(-1).*alpha.^3.*obj.Delta0.*obj.EI.*obj.kqtop.*pi.^2.*x.*sin(alpha.* ...
                            obj.L)+(-1).*alpha.*H.*obj.kqtop.*obj.L.*pi.^2.*x.*sin(alpha.*obj.L)+(-1).*alpha.* ...
                            obj.Delta0.*obj.gamma.*obj.kqtop.*P.*pi.^2.*x.*sin(alpha.*obj.L)+alpha.^5.* ...
                            obj.Delta0.*obj.EI.^2.*obj.L.^2.*sin(alpha.*(obj.L+(-1).*x))+alpha.^3.*obj.EI.*H.* ...
                            obj.L.^3.*sin(alpha.*(obj.L+(-1).*x))+alpha.^3.*obj.Delta0.*obj.EI.*obj.gamma.*obj.L.^2.* ...
                            P.*sin(alpha.*(obj.L+(-1).*x))+alpha.^5.*obj.delta0.*obj.EI.^2.*obj.L.^2.*pi.*sin( ...
                            alpha.*(obj.L+(-1).*x))+2.*alpha.*obj.delta0.*obj.gamma.*obj.kqtop.*obj.L.*P.*pi.*sin( ...
                            alpha.*(obj.L+(-1).*x))+alpha.^3.*obj.delta0.*obj.EI.*obj.gamma.*obj.L.^2.*P.*pi.*sin( ...
                            alpha.*(obj.L+(-1).*x))+(-1).*alpha.^3.*obj.Delta0.*obj.EI.^2.*pi.^2.*sin( ...
                            alpha.*(obj.L+(-1).*x))+(-1).*alpha.*obj.EI.*H.*obj.L.*pi.^2.*sin(alpha.*(obj.L+( ...
                            -1).*x))+(-1).*alpha.*obj.Delta0.*obj.EI.*obj.gamma.*P.*pi.^2.*sin(alpha.*(obj.L+( ...
                            -1).*x))+2.*alpha.*obj.delta0.*obj.gamma.*obj.kqtop.*obj.L.*P.*pi.*sin(alpha.*x)+ ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*((-2).*obj.gamma.*obj.kqtop.*P+alpha.*(alpha.^2.* ...
                            obj.EI.*obj.kqtop.*obj.L+(-1).*obj.EI.*obj.gamma.*P+obj.gamma.*obj.kqtop.*obj.L.*P).*sin(alpha.*obj.L) ...
                            ).*sin(obj.L.^(-1).*pi.*x)+cos(alpha.*obj.L).*(obj.kqtop.*(alpha.^2.*obj.L.^2.*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+alpha.^2.*obj.delta0.* ...
                            obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(-1).*(alpha.^2.*obj.Delta0.*obj.EI+H.* ...
                            obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2)+alpha.^2.*obj.EI.*(alpha.^2.*obj.Delta0.*obj.EI+ ...
                            H.*obj.L+obj.Delta0.*obj.gamma.*P).*(alpha.*obj.L+(-1).*pi).*(alpha.*obj.L+pi).*x+ ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(2.*obj.gamma.*obj.kqtop.*P+alpha.^2.*obj.EI.*obj.L.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P)).*sin(obj.L.^(-1).*pi.*x)));
                    else
                        v = (alpha.*obj.L+pi).^(-1).*((alpha.^4.*obj.EI.^2.*(obj.kqbot+obj.kqtop).*obj.L+2.* ...
                            obj.gamma.*obj.kqbot.*obj.kqtop.*P+alpha.^2.*obj.EI.*obj.gamma.*(obj.kqbot+obj.kqtop).*obj.L.*P).* ...
                            (alpha.*obj.L+(-1).*pi).*cos(alpha.*obj.L)+((-1).*alpha.*obj.L+pi).*(2.* ...
                            obj.gamma.*obj.kqbot.*obj.kqtop.*P+alpha.*(alpha.^4.*obj.EI.^3.*obj.L+obj.gamma.*(obj.EI.*( ...
                            obj.kqbot+obj.kqtop)+(-1).*obj.kqbot.*obj.kqtop.*obj.L).*P+alpha.^2.*obj.EI.*obj.L.*((-1).* ...
                            obj.kqbot.*obj.kqtop+obj.EI.*obj.gamma.*P)).*sin(alpha.*obj.L))).^(-1).*(obj.kqbot.* ...
                            obj.kqtop.*(alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.* ...
                            P)+(-1).*alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(-1) ...
                            .*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2)+obj.kqbot.* ...
                            obj.kqtop.*(alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.* ...
                            P)+alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(-1).*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*( ...
                            obj.L+(-1).*x))+(-1).*alpha.^4.*obj.Delta0.*obj.EI.*obj.kqbot.*obj.kqtop.*obj.L.^2.*cos( ...
                            alpha.*x)+(-1).*alpha.^2.*H.*obj.kqbot.*obj.kqtop.*obj.L.^3.*cos(alpha.*x)+( ...
                            -1).*alpha.^2.*obj.Delta0.*obj.gamma.*obj.kqbot.*obj.kqtop.*obj.L.^2.*P.*cos(alpha.*x) ...
                            +alpha.^4.*obj.delta0.*obj.EI.*obj.kqbot.*obj.kqtop.*obj.L.^2.*pi.*cos(alpha.*x)+ ...
                            alpha.^2.*obj.delta0.*obj.gamma.*obj.kqbot.*obj.kqtop.*obj.L.^2.*P.*pi.*cos(alpha.*x)+ ...
                            alpha.^2.*obj.Delta0.*obj.EI.*obj.kqbot.*obj.kqtop.*pi.^2.*cos(alpha.*x)+H.* ...
                            obj.kqbot.*obj.kqtop.*obj.L.*pi.^2.*cos(alpha.*x)+obj.Delta0.*obj.gamma.*obj.kqbot.* ...
                            obj.kqtop.*P.*pi.^2.*cos(alpha.*x)+alpha.^5.*obj.Delta0.*obj.EI.^2.*obj.kqbot.* ...
                            obj.L.^2.*sin(alpha.*obj.L)+alpha.^3.*obj.EI.*H.*obj.kqbot.*obj.L.^3.*sin(alpha.*obj.L)+ ...
                            alpha.^3.*obj.Delta0.*obj.EI.*obj.gamma.*obj.kqbot.*obj.L.^2.*P.*sin(alpha.*obj.L)+ ...
                            alpha.^5.*obj.delta0.*obj.EI.^2.*obj.kqbot.*obj.L.^2.*pi.*sin(alpha.*obj.L)+2.*alpha.* ...
                            obj.delta0.*obj.gamma.*obj.kqbot.*obj.kqtop.*obj.L.*P.*pi.*sin(alpha.*obj.L)+alpha.^3.* ...
                            obj.delta0.*obj.EI.*obj.gamma.*obj.kqbot.*obj.L.^2.*P.*pi.*sin(alpha.*obj.L)+(-1).* ...
                            alpha.^3.*obj.Delta0.*obj.EI.^2.*obj.kqbot.*pi.^2.*sin(alpha.*obj.L)+(-1).*alpha.* ...
                            obj.EI.*H.*obj.kqbot.*obj.L.*pi.^2.*sin(alpha.*obj.L)+(-1).*alpha.*obj.Delta0.*obj.EI.* ...
                            obj.gamma.*obj.kqbot.*P.*pi.^2.*sin(alpha.*obj.L)+alpha.^7.*obj.Delta0.*obj.EI.^3.* ...
                            obj.L.^2.*x.*sin(alpha.*obj.L)+(-1).*alpha.^5.*obj.Delta0.*obj.EI.*obj.kqbot.*obj.kqtop.* ...
                            obj.L.^2.*x.*sin(alpha.*obj.L)+alpha.^5.*obj.EI.^2.*H.*obj.L.^3.*x.*sin(alpha.*obj.L)+ ...
                            (-1).*alpha.^3.*H.*obj.kqbot.*obj.kqtop.*obj.L.^3.*x.*sin(alpha.*obj.L)+alpha.^5.* ...
                            obj.Delta0.*obj.EI.^2.*obj.gamma.*obj.L.^2.*P.*x.*sin(alpha.*obj.L)+(-1).*alpha.^3.* ...
                            obj.Delta0.*obj.gamma.*obj.kqbot.*obj.kqtop.*obj.L.^2.*P.*x.*sin(alpha.*obj.L)+(-1).* ...
                            alpha.^3.*obj.delta0.*obj.EI.*obj.gamma.*obj.kqbot.*obj.L.*P.*pi.*x.*sin(alpha.*obj.L)+ ...
                            alpha.^3.*obj.delta0.*obj.EI.*obj.gamma.*obj.kqtop.*obj.L.*P.*pi.*x.*sin(alpha.*obj.L)+( ...
                            -1).*alpha.^5.*obj.Delta0.*obj.EI.^3.*pi.^2.*x.*sin(alpha.*obj.L)+alpha.^3.* ...
                            obj.Delta0.*obj.EI.*obj.kqbot.*obj.kqtop.*pi.^2.*x.*sin(alpha.*obj.L)+(-1).*alpha.^3.* ...
                            obj.EI.^2.*H.*obj.L.*pi.^2.*x.*sin(alpha.*obj.L)+alpha.*H.*obj.kqbot.*obj.kqtop.*obj.L.* ...
                            pi.^2.*x.*sin(alpha.*obj.L)+(-1).*alpha.^3.*obj.Delta0.*obj.EI.^2.*obj.gamma.*P.* ...
                            pi.^2.*x.*sin(alpha.*obj.L)+alpha.*obj.Delta0.*obj.gamma.*obj.kqbot.*obj.kqtop.*P.* ...
                            pi.^2.*x.*sin(alpha.*obj.L)+(-1).*alpha.^5.*obj.Delta0.*obj.EI.^2.*obj.kqbot.* ...
                            obj.L.^2.*sin(alpha.*(obj.L+(-1).*x))+(-1).*alpha.^3.*obj.EI.*H.*obj.kqbot.*obj.L.^3.* ...
                            sin(alpha.*(obj.L+(-1).*x))+(-1).*alpha.^3.*obj.Delta0.*obj.EI.*obj.gamma.*obj.kqbot.* ...
                            obj.L.^2.*P.*sin(alpha.*(obj.L+(-1).*x))+(-1).*alpha.^5.*obj.delta0.*obj.EI.^2.* ...
                            obj.kqbot.*obj.L.^2.*pi.*sin(alpha.*(obj.L+(-1).*x))+(-2).*alpha.*obj.delta0.* ...
                            obj.gamma.*obj.kqbot.*obj.kqtop.*obj.L.*P.*pi.*sin(alpha.*(obj.L+(-1).*x))+(-1).* ...
                            alpha.^3.*obj.delta0.*obj.EI.*obj.gamma.*obj.kqbot.*obj.L.^2.*P.*pi.*sin(alpha.*(obj.L+( ...
                            -1).*x))+alpha.^3.*obj.Delta0.*obj.EI.^2.*obj.kqbot.*pi.^2.*sin(alpha.*(obj.L+(-1) ...
                            .*x))+alpha.*obj.EI.*H.*obj.kqbot.*obj.L.*pi.^2.*sin(alpha.*(obj.L+(-1).*x))+ ...
                            alpha.*obj.Delta0.*obj.EI.*obj.gamma.*obj.kqbot.*P.*pi.^2.*sin(alpha.*(obj.L+(-1).*x)) ...
                            +alpha.^5.*obj.Delta0.*obj.EI.^2.*obj.kqtop.*obj.L.^2.*sin(alpha.*x)+alpha.^3.* ...
                            obj.EI.*H.*obj.kqtop.*obj.L.^3.*sin(alpha.*x)+alpha.^3.*obj.Delta0.*obj.EI.*obj.gamma.* ...
                            obj.kqtop.*obj.L.^2.*P.*sin(alpha.*x)+(-1).*alpha.^5.*obj.delta0.*obj.EI.^2.* ...
                            obj.kqtop.*obj.L.^2.*pi.*sin(alpha.*x)+(-2).*alpha.*obj.delta0.*obj.gamma.*obj.kqbot.* ...
                            obj.kqtop.*obj.L.*P.*pi.*sin(alpha.*x)+(-1).*alpha.^3.*obj.delta0.*obj.EI.*obj.gamma.* ...
                            obj.kqtop.*obj.L.^2.*P.*pi.*sin(alpha.*x)+(-1).*alpha.^3.*obj.Delta0.*obj.EI.^2.* ...
                            obj.kqtop.*pi.^2.*sin(alpha.*x)+(-1).*alpha.*obj.EI.*H.*obj.kqtop.*obj.L.*pi.^2.* ...
                            sin(alpha.*x)+(-1).*alpha.*obj.Delta0.*obj.EI.*obj.gamma.*obj.kqtop.*P.*pi.^2.* ...
                            sin(alpha.*x)+alpha.^2.*obj.delta0.*obj.L.^2.*(2.*obj.gamma.*obj.kqbot.*obj.kqtop.*P+ ...
                            alpha.*(alpha.^4.*obj.EI.^3.*obj.L+obj.gamma.*(obj.EI.*(obj.kqbot+obj.kqtop)+(-1).*obj.kqbot.* ...
                            obj.kqtop.*obj.L).*P+alpha.^2.*obj.EI.*obj.L.*((-1).*obj.kqbot.*obj.kqtop+obj.EI.*obj.gamma.*P)).* ...
                            sin(alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x)+cos(alpha.*obj.L).*(obj.kqbot.*obj.kqtop.* ...
                            ((-1).*alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.* ...
                            P)+(-1).*alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2)+alpha.^2.*obj.EI.* ...
                            (obj.kqbot+obj.kqtop).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*((-1) ...
                            .*alpha.^2.*obj.L.^2+pi.^2).*x+(-1).*alpha.^2.*obj.delta0.*obj.L.^2.*( ...
                            alpha.^4.*obj.EI.^2.*(obj.kqbot+obj.kqtop).*obj.L+obj.gamma.*(2.*obj.kqbot.*obj.kqtop+ ...
                            alpha.^2.*obj.EI.*(obj.kqbot+obj.kqtop).*obj.L).*P).*sin(obj.L.^(-1).*pi.*x)));
                    end
                end
            else
                if obj.kqtop == 0
                    if obj.kqbot == 0
                        error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
                    elseif obj.kqbot == Inf
                        v = (-1).*H.*obj.L.*(alpha.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cos(alpha.*obj.L)+(-1) ...
                            .*obj.gamma.*P.*sin(alpha.*obj.L)).^(-1).*(alpha.*x.*cos(alpha.*obj.L)+(-1).* ...
                            sin(alpha.*obj.L)+sin(alpha.*(obj.L+(-1).*x)));
                    else
                        v = H.*obj.L.*((-1).*alpha.*obj.kqbot.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cos(alpha.* ...
                            obj.L)+(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*(obj.kqbot+alpha.^2.*obj.EI.*obj.L).*P).*sin( ...
                            alpha.*obj.L)).^(-1).*(alpha.*obj.kqbot.*x.*cos(alpha.*obj.L)+(-1).*(obj.kqbot+ ...
                            alpha.^2.*obj.EI.*x).*sin(alpha.*obj.L)+obj.kqbot.*sin(alpha.*(obj.L+(-1).*x)));
                    end
                elseif obj.kqtop == Inf
                    if obj.kqbot == 0
                        v = H.*obj.L.*(alpha.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cos(alpha.*obj.L)+(-1).* ...
                            obj.gamma.*P.*sin(alpha.*obj.L)).^(-1).*((-1).*alpha.*x.*cos(alpha.*obj.L)+ ...
                            sin(alpha.*x));
                    elseif obj.kqbot == Inf
                        v = (-1).*H.*obj.L.*(alpha.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cos((1/2).*alpha.* ...
                            obj.L)+(-2).*obj.gamma.*P.*sin((1/2).*alpha.*obj.L)).^(-1).*(alpha.*x.*cos(( ...
                            1/2).*alpha.*obj.L)+(-1).*sin((1/2).*alpha.*obj.L)+sin((1/2).*alpha.*(obj.L+( ...
                            -2).*x)));
                    else
                        v = H.*obj.L.*((-2).*obj.gamma.*obj.kqbot.*P+(2.*obj.gamma.*obj.kqbot.*P+alpha.^2.*obj.EI.*obj.L.* ...
                            (alpha.^2.*obj.EI+obj.gamma.*P)).*cos(alpha.*obj.L)+alpha.*(alpha.^2.*obj.EI.* ...
                            obj.kqbot.*obj.L+(-1).*obj.EI.*obj.gamma.*P+obj.gamma.*obj.kqbot.*obj.L.*P).*sin(alpha.*obj.L)).^( ...
                            -1).*(obj.kqbot+(-1).*(obj.kqbot+alpha.^2.*obj.EI.*x).*cos(alpha.*obj.L)+obj.kqbot.* ...
                            cos(alpha.*(obj.L+(-1).*x))+(-1).*obj.kqbot.*(cos(alpha.*x)+alpha.*x.*sin( ...
                            alpha.*obj.L))+alpha.*obj.EI.*sin(alpha.*x));
                    end
                else
                    if obj.kqbot == 0
                        v = (-1).*H.*obj.L.*((-1).*alpha.*obj.kqtop.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cos( ...
                            alpha.*obj.L)+(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*(obj.kqtop+alpha.^2.*obj.EI.*obj.L).*P).* ...
                            sin(alpha.*obj.L)).^(-1).*(alpha.*x.*((-1).*obj.kqtop.*cos(alpha.*obj.L)+ ...
                            alpha.*obj.EI.*sin(alpha.*obj.L))+obj.kqtop.*sin(alpha.*x));
                    elseif obj.kqbot == Inf
                        v = (-1).*H.*obj.L.*((-2).*obj.gamma.*obj.kqtop.*P+(2.*obj.gamma.*obj.kqtop.*P+alpha.^2.* ...
                            obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*cos(alpha.*obj.L)+alpha.*(alpha.^2.* ...
                            obj.EI.*obj.kqtop.*obj.L+(-1).*obj.EI.*obj.gamma.*P+obj.gamma.*obj.kqtop.*obj.L.*P).*sin(alpha.*obj.L) ...
                            ).^(-1).*((-1).*obj.kqtop+(obj.kqtop+alpha.^2.*obj.EI.*x).*cos(alpha.*obj.L)+(-1) ...
                            .*obj.kqtop.*cos(alpha.*(obj.L+(-1).*x))+obj.kqtop.*cos(alpha.*x)+(-1).* ...
                            alpha.*obj.EI.*sin(alpha.*obj.L)+alpha.*obj.kqtop.*x.*sin(alpha.*obj.L)+alpha.* ...
                            obj.EI.*sin(alpha.*(obj.L+(-1).*x)));
                    else
                        v = (-1).*H.*obj.L.*((-2).*obj.gamma.*obj.kqbot.*obj.kqtop.*P+(alpha.^4.*obj.EI.^2.*( ...
                            obj.kqbot+obj.kqtop).*obj.L+2.*obj.gamma.*obj.kqbot.*obj.kqtop.*P+alpha.^2.*obj.EI.*obj.gamma.*( ...
                            obj.kqbot+obj.kqtop).*obj.L.*P).*cos(alpha.*obj.L)+(-1).*alpha.*(alpha.^4.*obj.EI.^3.* ...
                            obj.L+obj.gamma.*(obj.EI.*(obj.kqbot+obj.kqtop)+(-1).*obj.kqbot.*obj.kqtop.*obj.L).*P+alpha.^2.* ...
                            obj.EI.*obj.L.*((-1).*obj.kqbot.*obj.kqtop+obj.EI.*obj.gamma.*P)).*sin(alpha.*obj.L)).^(-1).*( ...
                            (-1).*obj.kqbot.*obj.kqtop+(obj.kqbot.*obj.kqtop+alpha.^2.*obj.EI.*(obj.kqbot+obj.kqtop).*x).* ...
                            cos(alpha.*obj.L)+(-1).*obj.kqbot.*obj.kqtop.*cos(alpha.*(obj.L+(-1).*x))+obj.kqbot.* ...
                            obj.kqtop.*cos(alpha.*x)+(-1).*alpha.*obj.EI.*obj.kqbot.*sin(alpha.*obj.L)+(-1).* ...
                            alpha.^3.*obj.EI.^2.*x.*sin(alpha.*obj.L)+alpha.*obj.kqbot.*obj.kqtop.*x.*sin( ...
                            alpha.*obj.L)+alpha.*obj.EI.*obj.kqbot.*sin(alpha.*(obj.L+(-1).*x))+(-1).*alpha.* ...
                            obj.EI.*obj.kqtop.*sin(alpha.*x));
                    end
                end
            end
        end
        function m = firstOrderMoment(obj,P,H,x)
            if nargin < 4
                x = obj.position;
            end
            
            if P > 0
                error('Function only valid for compressive loads');
            else
                % Compressive loads should be positive
                P = -P; 
            end
            
            alpha = sqrt(P/obj.EI);
            if obj.includeInitialGeometricImperfections
                if obj.kqtop == 0
                    if obj.kqbot == 0
                        error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
                    elseif obj.kqbot == Inf
                        m = (-1).*obj.L.^(-1).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*(obj.L+( ...
                            -1).*x)+alpha.^2.*obj.delta0.*obj.EI.*sin(obj.L.^(-1).*pi.*x);
                    else
                        m = (-1).*obj.L.^(-1).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*(obj.L+( ...
                            -1).*x)+alpha.^2.*obj.delta0.*obj.EI.*sin(obj.L.^(-1).*pi.*x);
                    end
                elseif obj.kqtop == Inf
                    if obj.kqbot == 0
                        m = obj.L.^(-1).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*x+ ...
                            alpha.^2.*obj.delta0.*obj.EI.*sin(obj.L.^(-1).*pi.*x);
                    elseif obj.kqbot == Inf
                        m = (-1/2).*obj.L.^(-1).*pi.^(-1).*(alpha.^2.*obj.EI.*(4.*obj.delta0.*obj.L+obj.Delta0.* ...
                            pi.*(obj.L+(-2).*x))+(H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.*(obj.L+(-2).*x)+(-2).* ...
                            alpha.^2.*obj.delta0.*obj.EI.*obj.L.*pi.*sin(obj.L.^(-1).*pi.*x));
                    else
                        m = (1/2).*obj.L.^(-1).*(obj.EI+obj.kqbot.*obj.L).^(-1).*pi.^(-1).*((-1).*obj.kqbot.* ...
                            obj.L.^2.*((H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi+alpha.^2.*obj.EI.*(4.*obj.delta0+ ...
                            obj.Delta0.*pi))+2.*(obj.EI+obj.kqbot.*obj.L).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P).*pi.*x+2.*alpha.^2.*obj.delta0.*obj.EI.*obj.L.*(obj.EI+obj.kqbot.*obj.L).*pi.* ...
                            sin(obj.L.^(-1).*pi.*x));
                    end
                else
                    if obj.kqbot == 0
                        m = obj.L.^(-1).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*x+ ...
                            alpha.^2.*obj.delta0.*obj.EI.*sin(obj.L.^(-1).*pi.*x);
                    elseif obj.kqbot == Inf
                        m = (1/2).*obj.L.^(-1).*(obj.EI+obj.kqtop.*obj.L).^(-1).*pi.^(-1).*(obj.L.*((-4).* ...
                            alpha.^2.*obj.delta0.*obj.EI.*obj.kqtop.*obj.L+(-1).*(2.*obj.EI+obj.kqtop.*obj.L).*(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi)+2.*(obj.EI+obj.kqtop.*obj.L).*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.*x+2.*alpha.^2.* ...
                            obj.delta0.*obj.EI.*obj.L.*(obj.EI+obj.kqtop.*obj.L).*pi.*sin(obj.L.^(-1).*pi.*x));
                    else
                        m = (1/2).*obj.L.^(-1).*(obj.EI.*(obj.kqbot+obj.kqtop)+obj.kqbot.*obj.kqtop.*obj.L).^(-1).*pi.^( ...
                            -1).*(obj.kqbot.*obj.L.*((-4).*alpha.^2.*obj.delta0.*obj.EI.*obj.kqtop.*obj.L+(-1).*(2.* ...
                            obj.EI+obj.kqtop.*obj.L).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi)+ ...
                            2.*(obj.EI.*(obj.kqbot+obj.kqtop)+obj.kqbot.*obj.kqtop.*obj.L).*(alpha.^2.*obj.Delta0.*obj.EI+H.* ...
                            obj.L+obj.Delta0.*obj.gamma.*P).*pi.*x+2.*alpha.^2.*obj.delta0.*obj.EI.*obj.L.*(obj.EI.*( ...
                            obj.kqbot+obj.kqtop)+obj.kqbot.*obj.kqtop.*obj.L).*pi.*sin(obj.L.^(-1).*pi.*x));
                    end
                end
            else
                if obj.kqtop == 0
                    if obj.kqbot == 0
                        error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
                    elseif obj.kqbot == Inf
                        m = H.*((-1).*obj.L+x);
                    else
                        m = H.*((-1).*obj.L+x);
                    end
                elseif obj.kqtop == Inf
                    if obj.kqbot == 0
                        m = H.*x;
                    elseif obj.kqbot == Inf
                        m = H.*((-1/2).*obj.L+x);
                    else
                        m = H.*((-1/2).*obj.kqbot.*obj.L.^2.*(obj.EI+obj.kqbot.*obj.L).^(-1)+x);
                    end
                else
                    if obj.kqbot == 0
                        m = H.*x;
                    elseif obj.kqbot == Inf
                        m = (-1/2).*H.*obj.L.*(obj.EI+obj.kqtop.*obj.L).^(-1).*(2.*obj.EI+obj.kqtop.*obj.L)+H.*x;
                    else
                        m = H.*((-1).*obj.kqbot.*obj.L.*(2.*obj.EI+obj.kqtop.*obj.L).*(2.*obj.EI.*(obj.kqbot+obj.kqtop)+2.* ...
                            obj.kqbot.*obj.kqtop.*obj.L).^(-1)+x);
                    end
                end
            end            
        end
        function m = secondOrderMoment(obj,P,H,x)
            if nargin < 4
                x = obj.position;
            end
            
            % Check for zero axial load case
            if P == 0
                m = obj.firstOrderMoment(P,H,x);
                return
            elseif P > 0
                error('Function only valid for compressive loads');
            else
                % Compressive loads should be positive
                P = -P; 
            end
            
            alpha = sqrt(P/obj.EI);
            if obj.includeInitialGeometricImperfections
                if obj.kqtop == 0
                    if obj.kqbot == 0
                        error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
                    elseif obj.kqbot == Inf
                        m = alpha.^2.*obj.EI.*((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*(alpha.*obj.L.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*cos(alpha.*obj.L)+(-1).*obj.gamma.*P.*sin(alpha.* ...
                            obj.L)).^(-1).*((alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P)+alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(-1) ...
                            .*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*sin( ...
                            alpha.*(obj.L+(-1).*x))+obj.delta0.*pi.^2.*(alpha.*obj.L.*(alpha.^2.*obj.EI+ ...
                            obj.gamma.*P).*cos(alpha.*obj.L)+(-1).*obj.gamma.*P.*sin(alpha.*obj.L)).*sin(obj.L.^( ...
                            -1).*pi.*x));
                    else
                        m = alpha.^2.*obj.EI.*((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-1).*alpha.* ...
                            obj.kqbot.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cos(alpha.*obj.L)+(alpha.^4.* ...
                            obj.EI.^2.*obj.L+obj.gamma.*(obj.kqbot+alpha.^2.*obj.EI.*obj.L).*P).*sin(alpha.*obj.L)).^(-1) ...
                            .*(obj.kqbot.*((-1).*alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+ ...
                            obj.Delta0.*obj.gamma.*P)+(-1).*alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+ ...
                            obj.gamma.*P).*pi+(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2) ...
                            .*sin(alpha.*(obj.L+(-1).*x))+obj.delta0.*pi.^2.*((-1).*alpha.*obj.kqbot.*obj.L.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*cos(alpha.*obj.L)+(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*( ...
                            obj.kqbot+alpha.^2.*obj.EI.*obj.L).*P).*sin(alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x));
                    end
                elseif obj.kqtop == Inf
                    if obj.kqbot == 0
                        m = alpha.^2.*obj.EI.*((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-1).*obj.gamma.*P+ ...
                            alpha.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cot(alpha.*obj.L)).^(-1).*(((-1).* ...
                            alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+ ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*csc(alpha.*obj.L).*sin( ...
                            alpha.*x)+obj.delta0.*pi.^2.*((-1).*obj.gamma.*P+alpha.*obj.L.*(alpha.^2.*obj.EI+ ...
                            obj.gamma.*P).*cot(alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x));
                    elseif obj.kqbot == Inf
                        m = (-1/2).*alpha.^2.*obj.EI.*((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-2).* ...
                            obj.gamma.*P+alpha.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cot((1/2).*alpha.*obj.L)) ...
                            .^(-1).*(csc((1/2).*alpha.*obj.L).^2.*((alpha.^2.*obj.L.^2.*(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+alpha.^2.*obj.delta0.*obj.L.^2.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*pi+(-1).*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+ ...
                            obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*(obj.L+(-1).*x))+((-1).* ...
                            alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+ ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*x)+(-2).* ...
                            alpha.*obj.delta0.*obj.gamma.*obj.L.*P.*pi.*(sin(alpha.*(obj.L+(-1).*x))+sin( ...
                            alpha.*x)))+(-2).*obj.delta0.*pi.^2.*((-2).*obj.gamma.*P+alpha.*obj.L.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*cot((1/2).*alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x) ...
                            );
                    else
                        m = alpha.^2.*obj.EI.*((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-2).*obj.gamma.* ...
                            obj.kqbot.*P+(2.*obj.gamma.*obj.kqbot.*P+alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+ ...
                            obj.gamma.*P)).*cos(alpha.*obj.L)+alpha.*(alpha.^2.*obj.EI.*obj.kqbot.*obj.L+(-1).* ...
                            obj.EI.*obj.gamma.*P+obj.gamma.*obj.kqbot.*obj.L.*P).*sin(alpha.*obj.L)).^(-1).*(obj.kqbot.*(( ...
                            -1).*alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+ ...
                            (-1).*alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*( ...
                            obj.L+(-1).*x))+(-1).*obj.kqbot.*((-1).*alpha.^2.*obj.L.^2.*(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+alpha.^2.*obj.delta0.*obj.L.^2.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P).*pi.^2).*cos(alpha.*x)+2.*alpha.*obj.delta0.*obj.gamma.*obj.kqbot.* ...
                            obj.L.*P.*pi.*sin(alpha.*(obj.L+(-1).*x))+alpha.*((-1).*alpha.^2.*obj.EI.* ...
                            obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+obj.delta0.*obj.L.*(2.* ...
                            obj.gamma.*obj.kqbot.*P+alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*pi+obj.EI.* ...
                            (alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*sin(alpha.* ...
                            x)+obj.delta0.*pi.^2.*((-2).*obj.gamma.*obj.kqbot.*P+(2.*obj.gamma.*obj.kqbot.*P+ ...
                            alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*cos(alpha.*obj.L)+alpha.*( ...
                            alpha.^2.*obj.EI.*obj.kqbot.*obj.L+(-1).*obj.EI.*obj.gamma.*P+obj.gamma.*obj.kqbot.*obj.L.*P).* ...
                            sin(alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x));
                    end
                else
                    if obj.kqbot == 0
                        m = alpha.^2.*obj.EI.*((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*(alpha.^4.* ...
                            obj.EI.^2.*obj.L+obj.gamma.*(obj.kqtop+alpha.^2.*obj.EI.*obj.L).*P+(-1).*alpha.*obj.kqtop.*obj.L.* ...
                            (alpha.^2.*obj.EI+obj.gamma.*P).*cot(alpha.*obj.L)).^(-1).*((-1).*obj.kqtop.*((-1) ...
                            .*alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+ ...
                            alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*csc(alpha.*obj.L).*sin( ...
                            alpha.*x)+obj.delta0.*pi.^2.*(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*(obj.kqtop+ ...
                            alpha.^2.*obj.EI.*obj.L).*P+(-1).*alpha.*obj.kqtop.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P) ...
                            .*cot(alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x));
                    elseif obj.kqbot == Inf
                        m = alpha.^2.*obj.EI.*((-1).*alpha.^2.*obj.L.^2+pi.^2).^(-1).*((-2).*obj.gamma.* ...
                            obj.kqtop.*P+(2.*obj.gamma.*obj.kqtop.*P+alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+ ...
                            obj.gamma.*P)).*cos(alpha.*obj.L)+alpha.*(alpha.^2.*obj.EI.*obj.kqtop.*obj.L+(-1).* ...
                            obj.EI.*obj.gamma.*P+obj.gamma.*obj.kqtop.*obj.L.*P).*sin(alpha.*obj.L)).^(-1).*(obj.kqtop.*(( ...
                            -1).*alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+ ...
                            (-1).*alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*( ...
                            obj.L+(-1).*x))+(-1).*obj.kqtop.*((-1).*alpha.^2.*obj.L.^2.*(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+alpha.^2.*obj.delta0.*obj.L.^2.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P).*pi.^2).*cos(alpha.*x)+alpha.*(alpha.^2.*obj.EI.*obj.L.^2.*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+obj.delta0.*obj.L.*(2.*obj.gamma.* ...
                            obj.kqtop.*P+alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*pi+(-1).*obj.EI.*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*sin(alpha.*( ...
                            obj.L+(-1).*x))+2.*alpha.*obj.delta0.*obj.gamma.*obj.kqtop.*obj.L.*P.*pi.*sin(alpha.* ...
                            x)+obj.delta0.*pi.^2.*((-2).*obj.gamma.*obj.kqtop.*P+(2.*obj.gamma.*obj.kqtop.*P+ ...
                            alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*cos(alpha.*obj.L)+alpha.*( ...
                            alpha.^2.*obj.EI.*obj.kqtop.*obj.L+(-1).*obj.EI.*obj.gamma.*P+obj.gamma.*obj.kqtop.*obj.L.*P).* ...
                            sin(alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x));
                    else
                        m = alpha.^2.*obj.EI.*(alpha.*obj.L+pi).^(-1).*((alpha.^4.*obj.EI.^2.*(obj.kqbot+ ...
                            obj.kqtop).*obj.L+2.*obj.gamma.*obj.kqbot.*obj.kqtop.*P+alpha.^2.*obj.EI.*obj.gamma.*(obj.kqbot+ ...
                            obj.kqtop).*obj.L.*P).*(alpha.*obj.L+(-1).*pi).*cos(alpha.*obj.L)+((-1).*alpha.*obj.L+ ...
                            pi).*(2.*obj.gamma.*obj.kqbot.*obj.kqtop.*P+alpha.*(alpha.^4.*obj.EI.^3.*obj.L+obj.gamma.* ...
                            (obj.EI.*(obj.kqbot+obj.kqtop)+(-1).*obj.kqbot.*obj.kqtop.*obj.L).*P+alpha.^2.*obj.EI.*obj.L.*(( ...
                            -1).*obj.kqbot.*obj.kqtop+obj.EI.*obj.gamma.*P)).*sin(alpha.*obj.L))).^(-1).*(obj.kqbot.* ...
                            obj.kqtop.*(alpha.^2.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.* ...
                            P)+alpha.^2.*obj.delta0.*obj.L.^2.*(alpha.^2.*obj.EI+obj.gamma.*P).*pi+(-1).*( ...
                            alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*cos(alpha.*( ...
                            obj.L+(-1).*x))+obj.kqbot.*obj.kqtop.*((-1).*alpha.^2.*obj.L.^2.*(alpha.^2.* ...
                            obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+alpha.^2.*obj.delta0.*obj.L.^2.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*pi+(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.* ...
                            obj.gamma.*P).*pi.^2).*cos(alpha.*x)+(-1).*alpha.*obj.kqbot.*(alpha.^2.* ...
                            obj.EI.*obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+obj.delta0.*obj.L.* ...
                            (2.*obj.gamma.*obj.kqtop.*P+alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*pi+ ...
                            (-1).*obj.EI.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).* ...
                            sin(alpha.*(obj.L+(-1).*x))+(-1).*alpha.*obj.kqtop.*((-1).*alpha.^2.*obj.EI.* ...
                            obj.L.^2.*(alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P)+obj.delta0.*obj.L.*(2.* ...
                            obj.gamma.*obj.kqbot.*P+alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*pi+obj.EI.* ...
                            (alpha.^2.*obj.Delta0.*obj.EI+H.*obj.L+obj.Delta0.*obj.gamma.*P).*pi.^2).*sin(alpha.* ...
                            x)+(-1).*obj.delta0.*pi.^2.*((-2).*obj.gamma.*obj.kqbot.*obj.kqtop.*P+(alpha.^4.* ...
                            obj.EI.^2.*(obj.kqbot+obj.kqtop).*obj.L+2.*obj.gamma.*obj.kqbot.*obj.kqtop.*P+alpha.^2.*obj.EI.* ...
                            obj.gamma.*(obj.kqbot+obj.kqtop).*obj.L.*P).*cos(alpha.*obj.L)+(-1).*alpha.*( ...
                            alpha.^4.*obj.EI.^3.*obj.L+obj.gamma.*(obj.EI.*(obj.kqbot+obj.kqtop)+(-1).*obj.kqbot.*obj.kqtop.* ...
                            obj.L).*P+alpha.^2.*obj.EI.*obj.L.*((-1).*obj.kqbot.*obj.kqtop+obj.EI.*obj.gamma.*P)).*sin( ...
                            alpha.*obj.L)).*sin(obj.L.^(-1).*pi.*x));
                    end
                end
            else
                if obj.kqtop == 0
                    if obj.kqbot == 0
                        error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
                    elseif obj.kqbot == Inf
                        m = (-1).*alpha.^2.*obj.EI.*H.*obj.L.*(alpha.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cos( ...
                            alpha.*obj.L)+(-1).*obj.gamma.*P.*sin(alpha.*obj.L)).^(-1).*sin(alpha.*(obj.L+(-1) ...
                            .*x));
                    else
                        m = alpha.^2.*obj.EI.*H.*obj.kqbot.*obj.L.*((-1).*alpha.*obj.kqbot.*obj.L.*(alpha.^2.*obj.EI+ ...
                            obj.gamma.*P).*cos(alpha.*obj.L)+(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*(obj.kqbot+ ...
                            alpha.^2.*obj.EI.*obj.L).*P).*sin(alpha.*obj.L)).^(-1).*sin(alpha.*(obj.L+(-1).*x) ...
                            );
                    end
                elseif obj.kqtop == Inf
                    if obj.kqbot == 0
                        m = alpha.^2.*obj.EI.*H.*obj.L.*(alpha.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cos( ...
                            alpha.*obj.L)+(-1).*obj.gamma.*P.*sin(alpha.*obj.L)).^(-1).*sin(alpha.*x);
                    elseif obj.kqbot == Inf
                        m = (-1).*alpha.^2.*obj.EI.*H.*obj.L.*(alpha.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P).*cos( ...
                            (1/2).*alpha.*obj.L)+(-2).*obj.gamma.*P.*sin((1/2).*alpha.*obj.L)).^(-1).*sin( ...
                            (1/2).*alpha.*(obj.L+(-2).*x));
                    else
                        m = alpha.^2.*obj.EI.*H.*obj.L.*((-2).*obj.gamma.*obj.kqbot.*P+(2.*obj.gamma.*obj.kqbot.*P+ ...
                            alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*cos(alpha.*obj.L)+alpha.*( ...
                            alpha.^2.*obj.EI.*obj.kqbot.*obj.L+(-1).*obj.EI.*obj.gamma.*P+obj.gamma.*obj.kqbot.*obj.L.*P).* ...
                            sin(alpha.*obj.L)).^(-1).*(obj.kqbot.*cos(alpha.*(obj.L+(-1).*x))+(-1).* ...
                            obj.kqbot.*cos(alpha.*x)+alpha.*obj.EI.*sin(alpha.*x));
                    end
                else
                    if obj.kqbot == 0
                        m = (-1).*alpha.^2.*obj.EI.*H.*obj.kqtop.*obj.L.*((-1).*alpha.*obj.kqtop.*obj.L.*( ...
                            alpha.^2.*obj.EI+obj.gamma.*P).*cos(alpha.*obj.L)+(alpha.^4.*obj.EI.^2.*obj.L+obj.gamma.*( ...
                            obj.kqtop+alpha.^2.*obj.EI.*obj.L).*P).*sin(alpha.*obj.L)).^(-1).*sin(alpha.*x);
                    elseif obj.kqbot == Inf
                        m = (-1).*alpha.^2.*obj.EI.*H.*obj.L.*((-2).*obj.gamma.*obj.kqtop.*P+(2.*obj.gamma.* ...
                            obj.kqtop.*P+alpha.^2.*obj.EI.*obj.L.*(alpha.^2.*obj.EI+obj.gamma.*P)).*cos(alpha.*obj.L)+ ...
                            alpha.*(alpha.^2.*obj.EI.*obj.kqtop.*obj.L+(-1).*obj.EI.*obj.gamma.*P+obj.gamma.*obj.kqtop.* ...
                            obj.L.*P).*sin(alpha.*obj.L)).^(-1).*((-1).*obj.kqtop.*cos(alpha.*(obj.L+(-1).*x)) ...
                            +obj.kqtop.*cos(alpha.*x)+alpha.*obj.EI.*sin(alpha.*(obj.L+(-1).*x)));
                    else
                        m = alpha.^2.*obj.EI.*H.*obj.L.*(2.*obj.gamma.*obj.kqbot.*obj.kqtop.*P+(-1).*(alpha.^4.* ...
                            obj.EI.^2.*(obj.kqbot+obj.kqtop).*obj.L+2.*obj.gamma.*obj.kqbot.*obj.kqtop.*P+alpha.^2.*obj.EI.* ...
                            obj.gamma.*(obj.kqbot+obj.kqtop).*obj.L.*P).*cos(alpha.*obj.L)+alpha.*(alpha.^4.* ...
                            obj.EI.^3.*obj.L+obj.gamma.*(obj.EI.*(obj.kqbot+obj.kqtop)+(-1).*obj.kqbot.*obj.kqtop.*obj.L).*P+ ...
                            alpha.^2.*obj.EI.*obj.L.*((-1).*obj.kqbot.*obj.kqtop+obj.EI.*obj.gamma.*P)).*sin(alpha.*obj.L) ...
                            ).^(-1).*((-1).*obj.kqbot.*obj.kqtop.*cos(alpha.*(obj.L+(-1).*x))+obj.kqbot.* ...
                            obj.kqtop.*cos(alpha.*x)+alpha.*obj.EI.*(obj.kqbot.*sin(alpha.*(obj.L+(-1).*x))+( ...
                            -1).*obj.kqtop.*sin(alpha.*x)));
                    end
                end
            end
        end
        
        
        function vmax = maxFirstOrderDisplacement(obj,P,H)
            vmax = max(abs(obj.firstOrderDisplacement(P,H)));
        end
        function vmax = maxSecondOrderDisplacement(obj,P,H)
            vmax = max(abs(obj.secondOrderDisplacement(P,H)));
        end        
        function mmax = maxFirstOrderMoment(obj,P,H)
            mmax = max(abs(obj.firstOrderMoment(P,H)));
        end
        function mmax = maxSecondOrderMoment(obj,P,H)
            mmax = max(abs(obj.secondOrderMoment(P,H)));
        end
        
        
        function m2m1 = secondOrderMomentRatio(obj,P)
            m2m1 = max(abs(obj.secondOrderMoment(P,1)))/max(abs(obj.firstOrderMoment(P,1)));
            % @todo - this will be weird
        end
        function M1 = determineAppliedMoment(obj,P,M2,notionalLoadObject)
            if nargin < 4
                notionalLoadObject = notional_load;
            end
            
            % Estimate the necessary lateral load
            Hest1  = M2/obj.maxFirstOrderMoment(P,1.0);
            Ptotal = (1+obj.gamma)*P;
            B2     = obj.driftRatio(P);
            Hest   = notionalLoadObject.LoadEstimate(Hest1,Ptotal,B2);
            
            % fsolve to determine lateral load
            options = struct;
            options.Display = 'off';
            [H,~,exitflag] =  fsolve(...
                @(H)errorAppliedMoment(obj,P,H,M2,notionalLoadObject),...
                Hest,options);
            if exitflag <= 0
                error('fsolve could not find solution');
            end
            M1 = obj.maxFirstOrderMoment(P,H);
        end
        function [P,M2] = determinePeakLoad(obj,designM,designP,H,notionalLoadObject,Py,tauType)
            Hwnl = obj.Hwnl(-min(Py,obj.eulerLoad),H,notionalLoadObject);
            noImperfMoment = (obj.delta0 == 0 && obj.Delta0 == 0) || ~obj.includeInitialGeometricImperfections;
            if Hwnl == 0 && noImperfMoment
                % No lateral loads
                id = interactionDiagram2d(designM,designP);
                Pcr_design = id.findYgivenX(0,'negative');
                assert(~isempty(Pcr_design),'Could not find Pcr_design')
                
                Pguess = -0.8*min(Py,obj.eulerLoad);
                options.TolFun = 1.0e-12;
                options.TolX = abs(1.0e-8*Pguess);
                options.Display = 'off';
                [Pcr_analysis,~,exitflag,~] =  fsolve(...
                    @(P)errorCriticalLoad(obj,P,Py,tauType),...
                    Pguess,options);
                if exitflag <= 0
                    error('fsolve could not find solution');
                end
                
                if Pcr_design > Pcr_analysis
                    P  = Pcr_design;
                    M2 = 0;
                else
                    P  = Pcr_analysis;
                    id = interactionDiagram2d(designM,designP);
                    M2 = id.findXgivenY(P,'positive');
                    assert(~isempty(M2),'Could not find M2');
                end
                
            else
                Pguess = -0.5*min(Py,obj.eulerLoad);
                options.TolFun = 1.0e-8;
                options.TolX = abs(1.0e-5*Pguess);
                options.Display = 'off';
                [P,~,exitflag] =  fsolve(...
                    @(P)errorPeakLoad(obj,designM,designP,P,H,notionalLoadObject,Py,tauType),...
                    Pguess,options);
                if exitflag <= 0
                    options.TolX = abs(1.0e-8*Pguess);
                    [P,~,exitflag] =  fsolve(...
                        @(P)errorPeakLoad(obj,designM,designP,P,H,notionalLoadObject,Py,tauType),...
                        Pguess,options);
                    if exitflag <= 0
                        error('fsolve could not find solution');
                    end
                end
                tau  = AISC_tau(P/Py,tauType);
                obj2 = obj.get_copy_with_reduced_stiffness(tau,1);
                Hwnl = obj2.Hwnl(P,H,notionalLoadObject);
                M2   = obj2.maxSecondOrderMoment(P,Hwnl);
            end
        end
        function [Pmax,M2atPmax] = maximumLoad(obj,section,axis,...
                designStrengthType,...
                notionalLoadObject,...
                effectiveLengthFactorType,...
                columnStiffnessReduction,beamStiffnessReduction,tauType)
                           
            % Determine Design Beam Column Interaction
            sectionKL    = section;
            sectionKL.Lx = obj.L;
            sectionKL.Ly = obj.L;
            switch lower(effectiveLengthFactorType)
                case 'k'
                    sectionKL.Kx = obj.K;
                    sectionKL.Ky = obj.K;
                case 'storybasedk'
                    sectionKL.Kx = obj.storyBasedK;
                    sectionKL.Ky = obj.storyBasedK;
                case 'one'
                    sectionKL.Kx = 1.0;
                    sectionKL.Ky = 1.0;
                case 'zero'
                    sectionKL.Kx = 0.0;
                    sectionKL.Ky = 0.0;                    
                otherwise
                    error('Unknown effectiveLengthFactorType %s',effectiveLengthFactorType);
            end
            [designP,designM] = ...
                sectionKL.beamColumnInteraction2d(axis,['Factored' designStrengthType],'CompPos');
            
            Py = section.Pnco;
            obj2 = obj.get_copy_with_reduced_stiffness(...
                columnStiffnessReduction,beamStiffnessReduction);
            
            % Run axial only analysis to get Pn
            [Pmax,M2atPmax] = obj2.determinePeakLoad(designM,designP,0.0,notionalLoadObject,Py,tauType);        
        end
        function [P1,M1,P2,M2] = designInteraction(obj,section,axis,...
                designStrengthType,numPoints,...
                notionalLoadObject,...
                effectiveLengthFactorType,...
                columnStiffnessReduction,beamStiffnessReduction,tauType)
                           
            % Determine Design Beam Column Interaction
            sectionKL = section;
            sectionKL.Lx = obj.L;
            sectionKL.Ly = obj.L;
            switch lower(effectiveLengthFactorType)
                case 'k'
                    sectionKL.Kx = obj.K;
                    sectionKL.Ky = obj.K;
                case 'storybasedk'
                    sectionKL.Kx = obj.storyBasedK;
                    sectionKL.Ky = obj.storyBasedK;
                case 'one'
                    sectionKL.Kx = 1.0;
                    sectionKL.Ky = 1.0;
                case 'zero'
                    sectionKL.Kx = 0.0;
                    sectionKL.Ky = 0.0;
                otherwise
                    error('Unknown effectiveLengthFactorType %s',effectiveLengthFactorType);
            end
            [designP,designM] = ...
                sectionKL.beamColumnInteraction2d(axis,designStrengthType,'CompPos');
            
            
            % Initilize results
            P1 = zeros(numPoints,1);
            M1 = zeros(numPoints,1);
            P2 = zeros(numPoints,1);
            M2 = zeros(numPoints,1);
            
            Py = section.Pnco;
            obj2 = obj.get_copy_with_reduced_stiffness(...
                columnStiffnessReduction,beamStiffnessReduction);
            
            % Run axial only analysis to get Pn
            [p,m2] = obj2.determinePeakLoad(designM,designP,0.0,notionalLoadObject,Py,tauType);
            P1(1) = p;
            M1(1) = 0.0;
            P2(1) = p;
            M2(1) = m2;
            
            % Run nonproportional analyses at different axial loads
            Ps = linspace(P1(1),0,numPoints);
            for i = 2:length(Ps)
                p = Ps(i);
                tau  = AISC_tau(p/Py,tauType);
                obj2 = obj.get_copy_with_reduced_stiffness(...
                    tau*columnStiffnessReduction,beamStiffnessReduction);
                id = interactionDiagram2d(designM,designP);
                m2 = id.findXgivenY(p,'Positive');
                m1 = obj2.determineAppliedMoment(p,m2,notionalLoadObject);
                P1(i) = p;
                M1(i) = m1;
                P2(i) = p;
                M2(i) = m2;
            end
        end
        function err = errorEIeff_d(obj,P1,x1,vmax,EIeff)
            obj2 = obj.get_copy_with_reduced_stiffness(EIeff/obj.EI,1);
            err = vmax-obj2.maxSecondOrderDisplacement(P1,x1);
        end
        function err = errorEIeff_f(obj,P1,x1,vmax,EIeff)
            obj2 = obj.get_copy_with_reduced_stiffness(EIeff/obj.EI,1);
            err = vmax-obj2.maxSecondOrderMoment(P1,x1);
        end
        function [P2e,M2e] = impliedInteraction(obj,P1_FN,M1_FN,...
            notionalLoadObject,...
            columnStiffnessReduction,beamStiffnessReduction,tauType,Py)
        
            P2e = nan(size(P1_FN));
            M2e = nan(size(M1_FN));
            for iPoint = 1:length(P2e)
                P = P1_FN(iPoint);
                
                if -P >= Py
                    continue
                end
                
                tau = AISC_tau(P/Py,tauType);
                obj2 = obj.get_copy_with_reduced_stiffness(...
                    tau*columnStiffnessReduction,beamStiffnessReduction);      
                
                if -P >= obj2.eulerLoad
                    continue
                end
                
                H    = obj2.determineAppliedLoadFromM1(P,M1_FN(iPoint));
                Hwnl = obj2.Hwnl(P,H,notionalLoadObject);
                
                P2e(iPoint) = P;
                M2e(iPoint) = obj2.maxSecondOrderMoment(P,Hwnl);
            end
        end
        function [drift_1,drift_2,driftRatio] = computeDrifts(obj,P1,M1)
            assert(isequal(size(P1),size(M1)),'The size of P1 and M1 must be the same');
            drift_1 = nan(size(P1));
            drift_2 = nan(size(P1));
            driftRatio = nan(size(P1));
            
            for i = 1:numel(P1)
                iP  = P1(i);
                iM1 = M1(i);
                iH  = obj.determineAppliedLoadFromM1(iP,iM1);
                
                drift_1(i) = obj.maxFirstOrderDisplacement(iP,iH)/obj.L;
                drift_2(i) = obj.maxSecondOrderDisplacement(iP,iH)/obj.L;
                driftRatio(i) = obj.driftRatio(iP);
            end
        end 
        function p = determineLoadForMomentRatio(obj,momentRatio,...
                columnStiffnessReduction,beamStiffnessReduction,tauType,Py_tau)
            
            % Check for quick exit
            tau = AISC_tau(1,tauType);
            if tau ~= 0
                obj2 = obj.get_copy_with_reduced_stiffness(...
                    tau*columnStiffnessReduction,beamStiffnessReduction);
                if obj2.secondOrderMomentRatio(-Py_tau) < momentRatio;
                    p = Py_tau;
                    return
                end
            end
            
            % Estimate the necessary lateral load
            Pest   = 0.95*min(Py_tau,obj.eulerLoad);
            
            % fsolve to determine lateral load
            options = struct;
            options.Display = 'off';
            [p,~,exitflag] =  fsolve(...
                @(P)errorPforMomentRatio(obj,P,momentRatio,columnStiffnessReduction,beamStiffnessReduction,tauType,Py_tau),...
                Pest,options);
            if exitflag <= 0
                %error('fsolve could not find solution');
                fprintf('fsolve could not find solution\n');
                p = NaN;
            end
        end
        function obj2 = get_copy_with_reduced_stiffness(obj,column_reduction,beam_reduction)
            obj2 = BenchmarkAnalysis2d_Elastic_Sidesway_Uninhibited(...
                obj.EI*column_reduction,...
                obj.L,...
                obj.kqtop*beam_reduction,...
                obj.kqbot*beam_reduction,...
                obj.gamma,...
                obj.delta0,...    
                obj.Delta0);
            obj2.includeInitialGeometricImperfections = obj.includeInitialGeometricImperfections;
        end
    end
    
    methods (Static)
        function t = type()
            t = 'SideswayUninhibited';
        end
        function t = type2()
            t = 'U';
        end
    end
end



function x = errorPeakLoad(obj,designM,designP,P,H,notionalLoadObject,Py,tauType)
tau = AISC_tau(P/Py,tauType);
obj2 = obj.get_copy_with_reduced_stiffness(tau,1);
if P < -obj2.eulerLoad
    x = NaN;
else
    Hwnl = obj2.Hwnl(P,H,notionalLoadObject);
    M2   = obj2.maxSecondOrderMoment(P,Hwnl);
    id   = interactionDiagram2d(designM,designP);
    x    = id.checkPoints(M2,P)-1;
end
end

function x = errorPforMomentRatio(obj,P,momentRatio,columnStiffnessReduction,beamStiffnessReduction,tauType,Py_tau)

if P < 0
    x = NaN;
else
    tau = AISC_tau(P/Py_tau,tauType);
    obj2 = obj.get_copy_with_reduced_stiffness(...
        tau*columnStiffnessReduction,beamStiffnessReduction);

    if P >= obj2.eulerLoad
        x = NaN;
    else
        x = obj2.secondOrderMomentRatio(-P)-momentRatio;
    end
end

end

function x = errorAppliedMoment(obj,P,H,M2,notionalLoadObject)
    Hwnl = obj.Hwnl(P,H,notionalLoadObject);
    x    = obj.maxSecondOrderMoment(P,Hwnl) - M2;
end

function x = errorK(obj,K)
alpha = pi/(K*obj.L);
if obj.kqtop == 0
    if obj.kqbot == 0
        error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
    elseif obj.kqbot == Inf
        x = (-1).*alpha.*(1+obj.gamma).*obj.L.*cos(alpha.*obj.L)+obj.gamma.*sin(alpha.*obj.L);
    else
        x = (-1).*alpha.*(1+obj.gamma).*obj.kqbot.*obj.L.*cos(alpha.*obj.L)+(obj.gamma.*obj.kqbot+ ...
            alpha.^2.*obj.EI.*(1+obj.gamma).*obj.L).*sin(alpha.*obj.L);
    end
elseif obj.kqtop == Inf
    if obj.kqbot == 0
        x = alpha.*(1+obj.gamma).*obj.L.*cos(alpha.*obj.L)+(-1).*obj.gamma.*sin(alpha.*obj.L);
    elseif obj.kqbot == Inf
        x = (-2).*obj.gamma.*((-1)+cos(alpha.*obj.L))+(-1).*alpha.*(1+obj.gamma).*obj.L.*sin( ...
            alpha.*obj.L);
    else
        x = 2.*obj.gamma.*obj.kqbot+(-1).*(2.*obj.gamma.*obj.kqbot+alpha.^2.*obj.EI.*(1+obj.gamma).*obj.L) ...
            .*cos(alpha.*obj.L)+alpha.*(obj.EI.*obj.gamma+(-1).*(1+obj.gamma).*obj.kqbot.*obj.L).*sin( ...
            alpha.*obj.L);
    end
else
    if obj.kqbot == 0
        x = (-1).*alpha.*(1+obj.gamma).*obj.kqtop.*obj.L.*cos(alpha.*obj.L)+(obj.gamma.*obj.kqtop+ ...
            alpha.^2.*obj.EI.*(1+obj.gamma).*obj.L).*sin(alpha.*obj.L);
    elseif obj.kqbot == Inf
        x = alpha.^(-1).*((-2).*obj.gamma.*obj.kqtop+(2.*obj.gamma.*obj.kqtop+alpha.^2.*obj.EI.*( ...
            1+obj.gamma).*obj.L).*cos(alpha.*obj.L)+alpha.*((-1).*obj.EI.*obj.gamma+(1+obj.gamma).* ...
            obj.kqtop.*obj.L).*sin(alpha.*obj.L));
    else
        x = (-2).*obj.gamma.*obj.kqbot.*obj.kqtop+(2.*obj.gamma.*obj.kqbot.*obj.kqtop+alpha.^2.*obj.EI.*( ...
            1+obj.gamma).*(obj.kqbot+obj.kqtop).*obj.L).*cos(alpha.*obj.L)+(-1).*alpha.*(obj.EI.* ...
            obj.gamma.*(obj.kqbot+obj.kqtop)+(1+obj.gamma).*(alpha.^2.*obj.EI.^2+(-1).*obj.kqbot.* ...
            obj.kqtop).*obj.L).*sin(alpha.*obj.L);
    end
end
end

function x = errorCriticalLoad(obj,P,Py,tauType)
tau = AISC_tau(P/Py,tauType);
obj2 = obj.get_copy_with_reduced_stiffness(tau,1);
x = -P - obj2.eulerLoad;
end


% if obj.kqtop == 0
%     if obj.kqbot == 0
%         error('Structure is unstable for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
%     elseif obj.kqbot == Inf
%         error('Function not yet implemented for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
%     else
%         error('Function not yet implemented for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
%     end
% elseif obj.kqtop == Inf
%     if obj.kqbot == 0
%         error('Function not yet implemented for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
%     elseif obj.kqbot == Inf
%         error('Function not yet implemented for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
%     else
%         error('Function not yet implemented for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
%     end
% else
%     if obj.kqbot == 0
%         error('Function not yet implemented for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
%     elseif obj.kqbot == Inf
%         error('Function not yet implemented for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
%     else
%         error('Function not yet implemented for kqtop = %g, kqbot = %g',obj.kqtop,obj.kqbot);
%     end
% end
